// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008123839_AddProductsTable")]
    partial class AddProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Bánh quy, kẹo, snack, rong biển"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước khoáng, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai, sữa đặc"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì & Thực phẩm ăn liền",
                            Description = "Mì gói, phở khô, cháo ăn liền, miến"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Nấu ăn",
                            Description = "Nước mắm, nước tương, dầu ăn, hạt nêm"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Gạo & Ngũ cốc",
                            Description = "Gạo, đậu, ngũ cốc, yến mạch"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ hộp & Thực phẩm đóng gói",
                            Description = "Cá hộp, thịt hộp, pate, thực phẩm đóng gói"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hòa tan, cà phê rang xay, trà túi lọc"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Nước chấm & Sốt",
                            Description = "Tương ớt, tương cà, sốt mayonnaise, nước chấm"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Chổi, khăn lau, móc áo, đồ dùng nhà bếp"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Hóa mỹ phẩm",
                            Description = "Dầu gội, sữa tắm, kem đánh răng, xà phòng"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Giấy & Đồ dùng cá nhân",
                            Description = "Giấy vệ sinh, khăn giấy, khẩu trang, bông tẩy trang"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ dùng học tập",
                            Description = "Bút, vở, thước, tập, dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Xúc xích, cá viên, bò viên, thực phẩm đông lạnh"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Đồ dùng trẻ em",
                            Description = "Sữa trẻ em, bánh ăn dặm, khăn và đồ dùng cho bé"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Số 25, đường Nguyễn Huệ",
                            CustomerName = "Nguyễn Thị Lan",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            Province = "Đồng Tháp",
                            RewardPoints = 250,
                            Ward = "Phường 1"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Số 50, đường Lê Lợi",
                            CustomerName = "Trần Văn Minh",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            Province = "Đồng Tháp",
                            RewardPoints = 120,
                            Ward = "Phường 2"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Số 10, đường Nguyễn Trãi",
                            CustomerName = "Lê Thị Hồng",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            Province = "Đồng Tháp",
                            RewardPoints = 35,
                            Ward = "Phường 1"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Số 88, đường Lý Thường Kiệt",
                            CustomerName = "Phạm Hoàng Nam",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0939112233",
                            Province = "Đồng Tháp",
                            RewardPoints = 680,
                            Ward = "Phường 3"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Số 15, đường Hùng Vương",
                            CustomerName = "Đặng Thu Thảo",
                            District = "Thành phố Sa Đéc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0945223344",
                            Province = "Đồng Tháp",
                            RewardPoints = 310,
                            Ward = "Phường 2"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Số 102, đường Trần Hưng Đạo",
                            CustomerName = "Võ Văn Tuấn",
                            District = "Thành phố Sa Đéc",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0978334455",
                            Province = "Đồng Tháp",
                            RewardPoints = 150,
                            Ward = "Phường 1"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Số 42, đường Điện Biên Phủ",
                            CustomerName = "Bùi Thị Mai",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918445566",
                            Province = "Đồng Tháp",
                            RewardPoints = 50,
                            Ward = "Phường Mỹ Phú"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Số 79, đường Nguyễn Sinh Cung",
                            CustomerName = "Ngo Thanh Tung",
                            District = "Thành phố Sa Đéc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0927556677",
                            Province = "Đồng Tháp",
                            RewardPoints = 290,
                            Ward = "Phường 2"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Số 14, đường Võ Trường Toản",
                            CustomerName = "Dương Quốc Bảo",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0966667788",
                            Province = "Đồng Tháp",
                            RewardPoints = 180,
                            Ward = "Phường 4"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Số 63, đường Phạm Hữu Lầu",
                            CustomerName = "Hoàng Kim Ngân",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0908778899",
                            Province = "Đồng Tháp",
                            RewardPoints = 15,
                            Ward = "Phường 6"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "Số 05, đường Nguyễn Huệ",
                            CustomerName = "Đỗ Duy Khoa",
                            District = "Thành phố Hồng Ngự",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0931889900",
                            Province = "Đồng Tháp",
                            RewardPoints = 95,
                            Ward = "Phường An Thạnh"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Số 118, đường Quốc Lộ 30",
                            CustomerName = "Trịnh Tuyết Mai",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0949990011",
                            Province = "Đồng Tháp",
                            RewardPoints = 820,
                            Ward = "Phường Mỹ Trà"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Số 200, đường Lê Đại Hành",
                            CustomerName = "Lý Văn Đức",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0981001122",
                            Province = "Đồng Tháp",
                            RewardPoints = 40,
                            Ward = "Phường Mỹ Phú"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8934567890001",
                            CategoryId = 1,
                            Price = 125000m,
                            ProductName = "Bánh quy bơ Danisa 454g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8934567890002",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước ngọt Coca Cola lon 330ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8934567890003",
                            CategoryId = 3,
                            Price = 7500m,
                            ProductName = "Sữa tươi Vinamilk 180ml",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8934567890004",
                            CategoryId = 4,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo tôm chua cay 75g",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8934567890005",
                            CategoryId = 5,
                            Price = 32000m,
                            ProductName = "Nước mắm Nam Ngư 500ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8934567890006",
                            CategoryId = 6,
                            Price = 145000m,
                            ProductName = "Gạo ST25 túi 5kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8934567890007",
                            CategoryId = 7,
                            Price = 28000m,
                            ProductName = "Cá hộp ba cô gái 155g",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8934567890008",
                            CategoryId = 8,
                            Price = 65000m,
                            ProductName = "Cà phê hòa tan Trung Nguyên 3in1",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8934567890009",
                            CategoryId = 9,
                            Price = 18000m,
                            ProductName = "Tương ớt Chinsu 250g",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8934567890010",
                            CategoryId = 10,
                            Price = 32000m,
                            ProductName = "Nước rửa chén Sunlight 750ml",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8934567890011",
                            CategoryId = 11,
                            Price = 115000m,
                            ProductName = "Dầu gội Clear 650g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8934567890012",
                            CategoryId = 12,
                            Price = 28000m,
                            ProductName = "Khăn giấy Pulppy 3 lớp",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8934567890013",
                            CategoryId = 13,
                            Price = 5000m,
                            ProductName = "Bút bi Thiên Long TL-027",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8934567890014",
                            CategoryId = 14,
                            Price = 42000m,
                            ProductName = "Xúc xích CP gói 200g",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8934567890015",
                            CategoryId = 15,
                            Price = 68000m,
                            ProductName = "Bánh ăn dặm Gerber cho bé",
                            StockQuantity = 35
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
