// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261008114329_UpdateCustomerSeedData")]
    partial class UpdateCustomerSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Bánh quy, kẹo, snack, rong biển"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát",
                            Description = "Nước ngọt, nước khoáng, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai, sữa đặc"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì & Thực phẩm ăn liền",
                            Description = "Mì gói, phở khô, cháo ăn liền, miến"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Nấu ăn",
                            Description = "Nước mắm, nước tương, dầu ăn, hạt nêm"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Gạo & Ngũ cốc",
                            Description = "Gạo, đậu, ngũ cốc, yến mạch"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ hộp & Thực phẩm đóng gói",
                            Description = "Cá hộp, thịt hộp, pate, thực phẩm đóng gói"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hòa tan, cà phê rang xay, trà túi lọc"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Nước chấm & Sốt",
                            Description = "Tương ớt, tương cà, sốt mayonnaise, nước chấm"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ dùng gia đình",
                            Description = "Chổi, khăn lau, móc áo, đồ dùng nhà bếp"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Hóa mỹ phẩm",
                            Description = "Dầu gội, sữa tắm, kem đánh răng, xà phòng"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Giấy & Đồ dùng cá nhân",
                            Description = "Giấy vệ sinh, khăn giấy, khẩu trang, bông tẩy trang"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ dùng học tập",
                            Description = "Bút, vở, thước, tập, dụng cụ học tập"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Xúc xích, cá viên, bò viên, thực phẩm đông lạnh"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Đồ dùng trẻ em",
                            Description = "Sữa trẻ em, bánh ăn dặm, khăn và đồ dùng cho bé"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "15 Nguyễn Huệ",
                            CustomerName = "Nguyễn Thị Lan",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            Province = "Đồng Tháp",
                            RewardPoints = 250,
                            Ward = "Phường 1"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "28 Lê Lợi",
                            CustomerName = "Trần Văn Minh",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            Province = "Đồng Tháp",
                            RewardPoints = 120,
                            Ward = "Phường 2"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "42 Nguyễn Trãi",
                            CustomerName = "Lê Thị Hồng",
                            District = "Thành phố Cao Lãnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            Province = "Đồng Tháp",
                            RewardPoints = 35,
                            Ward = "Phường 1"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
